### ISSUE TITLE
Timestamp

### ISSUE THREAD

**Issue by moon47usaco** [zamp/vid2vid#11]
Suggest adding time to the renderpasses output to console to monitor time overall and per pass.

```
import os
import shutil
import processors
import util
import configparser
import uuid
#timestamp
from datetime import datetime
...
...
...
	for config_name in config:
		if not config_name.startswith("RenderPass"):
			continue

		arr = config_name.split(".")
		name = arr[0]
		type = arr[1]
		dt = datetime.now()

		print(f"Executing pass: {name} ({type})", dt.strftime("%H:%M:%S"))
...
...
...
```

**Comment by axb2035** [comment]
The [Add pass and overall timers](https://github.com/zamp/vid2vid/pull/9) PR covers this suggestion and was merged into the code a day or so ago. Update to get the latest code.

**Comment by moon47usaco** [comment]
I still like the timestamps for the passes, that way I can see how much time has passed since the start plus each pass while it is running.
Plus the extra line in the cmd window makes it look a bit messy and hard to read with all the passes that take 0 time like copy del passes... (I copy everything into a save folder for each pass [comfy, eb, alpha] to monitor how each affects the final)

I do like the overall time taken at the end...
