### ISSUE TITLE
Multiple frames per extra prompts

### ISSUE THREAD

**Issue by zamp** [zamp/vid2vid#8]
Instead of adding multiple [ExtraPrompt] with one frame each it's better to have one [ExtraPrompt] with Frames = 1,2,3,4,5 etc.

**Comment by moon47usaco** [comment]
And a way to specify a range of values as well. Ideally something like: 
Frames = 1-4, 6, 8
So essentially 1 to 8 skipping 5 and 7 without having to write out 1, 2, 3, 4.
